server:
  port: 8084

bot:
  username: schulan_bot
  token: ${BOT_TOKEN:----------------------------------}

logging:
  level:
    root: info
  file:
    name: ./logs/application.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message