server:
  port: ${DISPATCHER_PORT:8084}
  ssl:
    enabled: false

# (terminal) ssh -R 80:localhost:<port> serveo.net to create tunnel
# ssh -R 80:localhost:8080 nokey@localhost.run
bot:
  uri: ${TG_BOT_URI:https://5893da02c19c26.lhr.life}
  username: ${TG_BOT_NAME:schulan_bot}
  token: ${TG_BOT_TOKEN:---------------------------}

logging:
  level:
    root: info
  file:
    name: ./logs/dispatcher.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5673}
    username: ${RABBIT_USERNAME:redfan}
    password: ${RABBIT_PASSWORD:redfan}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE:text_message_update_queue}
      doc-message-update: ${RABBIT_DOC_MESSAGE_UPDATE_QUEUE:doc_message_update_queue}
      photo-message-update: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE:photo_message_update_queue}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE:answer_message_queue}