server:
  port: 8084
  ssl:
    enabled: false # it needs for correct working Webhook
#   app - http -> proxyServer -> https -> Telegram server
#   app - http <- proxyServer <- https <- Telegram server

# (terminal) ssh -R 80:localhost:<port> serveo.net to create tunnel
bot:
  uri: https://dd4fbe31781d144183591b70b8ba6804.serveo.net  # final uri will be <bot.uri> + </callback>(from telegram lib) + </update>
  username: schulan_bot
  token: ${BOT_TOKEN:-----------------------------------------}

logging:
  level:
    root: info
  file:
    name: ./logs/dispatcher.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: redfan
    password: redfan
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message