server:
  port: ${MAIL_SERVICE_PORT:8087}

service:
  activation:
    uri: ${ACTIVATION_URI:http://127.0.0.1:8086/users/activation/{id}}

logging:
  level:
    root: info
  file:
    name: ./logs/mail-service.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:465}
    protocol: ${MAIL_PROTOCOL:smtps}
    username: ${MAIL_USERNAME:-------------------}
    password: ${MAIL_PASSWORD:--------------------}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5673}
    username: ${RABBIT_USERNAME:redfan}
    password: ${RABBIT_PASSWORD:redfan}
    queues:
      registration-mail: ${RABBIT_REGISTRATION_MAIL_QUEUE:registration_mail}