server:
  port: 8085

logging:
  level:
    root: info
  file:
    name: ./logs/node.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/shulan
    driver-class-name: org.postgresql.Driver
  jpa:
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2ddl:
            auto: validate
          jdbc:
            fetch_size: 100
            batch_size: 100
  flyway:
    url: jdbc:postgresql://localhost:5433/shulan
    locations: classpath:db/migration
    user: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: redfan
    password: redfan
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message