server:
  port: 8085

logging:
  level:
    root: info
  file:
    name: ./logs/node.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: redfan
    password: redfan
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message