server:
  port: 8085

service:
  mail:
    uri: http://127.0.0.1:8087/mail/send

app:
  link-for-files: http://127.0.0.1:8086/
  doc-secret: YwgQfxWvap1sEMY63pNU
  photo-secret: C220VomyPV0yTNTqiK8j
  user-secret: hhuYny0KKbu5kBGWd2cK

bot:
  token: ${BOT_TOKEN:---------------------}
  service:
    file-info:
      uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file-storage:
      uri: https://api.telegram.org/file/bot{token}/{filePath}

logging:
  level:
    root: info
  file:
    name: ./logs/node.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/shulan
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          fetch_size: 100
          batch_size: 100
  flyway:
    url: jdbc:postgresql://localhost:5433/shulan
    locations: classpath:db/migration
    user: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: redfan
    password: redfan
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message