server:
  port: 8086

app:
  doc-secret: YwgQfxWvap1sEMY63pNU
  photo-secret: C220VomyPV0yTNTqiK8j
  user-secret: hhuYny0KKbu5kBGWd2cK

logging:
  level:
    root: info
  file:
    name: ./logs/rest-service.log
  logback:
    rolling policy:
      max-history: 3
      max-file-size: 1MB

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/shulan
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          fetch_size: 100
          batch_size: 100